Repository onlinkers/first-prototype, pull requests merged in 2019-08, with the labels that each got.

#11 Help Review for Linkathon! (DONT MERGE)
  src/assets/eventData.js
  src/assets/sass/components/_landing.sass
  src/components/Map.vue
  src/components/cards/eventDetailed.vue
  src/components/cards/eventDisplay.vue
  src/components/ui/popularEventsWindow.vue
  src/views/Landing.vue
Labels: development, feature

#12 Styled Event Window Popup and Nearby Events Tab
  src/assets/eventData.js
  src/assets/icons/star-hollow.png
  src/assets/icons/star-hollow.svg
  src/assets/sass/_variables.sass
  src/assets/sass/components/_landing.sass
  src/components/cards/eventDetailed.vue
  src/components/cards/eventDisplay.vue
Labels: design, development

#14 Merge UI Branch (Working)
  src/assets/eventData.js
  src/assets/icons/star-hollow.png
  src/assets/icons/star-hollow.svg
  src/assets/sass/_variables.sass
  src/assets/sass/components/_landing.sass
  src/components/Map.vue
  src/components/cards/eventDetailed.vue
  src/components/cards/eventDisplay.vue
  src/components/ui/popularEventsWindow.vue
  src/views/Landing.vue
Labels: design, documentation, feature
